import Head from 'next/head'
import styles from '../styles/Home.module.css'

import React, { useState, useEffect } from 'react';
import { signIn, signOut, useSession } from 'next-auth/client';

export default function Home() {
  const [phantom, setPhantom] = useState();
  const [session] = useSession();

  useEffect(async () => {
    if(window.solana) {
      setPhantom(window.solana);
      await window.solana.connect();
    }
  }, []);

  async function fetchNonce() {
    
    const response = await fetch('/api/login');
  
    if(response.status != 200)
      throw new Error("nonce could not be retrieved");

    const { nonce } = await response.json();
    
    return nonce;
  }

  async function login() {

    const nonce = await fetchNonce();

    const message = `Sign this message for authenticating with your wallet. Nonce: ${nonce}`;
    const encodedMessage = new TextEncoder().encode(message);
    const signedMessage = await solana.request({
      method: "signMessage",
      params: {
        message: encodedMessage,
      },
    });

    signIn('credentials',
      {
        publicKey: signedMessage.publicKey,
        signature: signedMessage.signature,
        callbackUrl: `${window.location.origin}/`
      }
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!phantom && <p className={styles.description}>This sample requires Phantom Wallet</p>}

        {phantom && !session && <button onClick={login}>Login with Phantom</button> }

        {phantom && session && 
          <>
           <p className={styles.description}> Welcome {session?.user?.name}</p>
           <button onClick={signOut}>Logout</button>
          </> 
        }

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

